# Generated by Django 3.2.2 on 2021-05-08 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoomDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=100)),
                ('room_status', models.CharField(choices=[('Available', 'available'), ('Unavailable', 'unavailable')], default='Unavailable', max_length=255)),
                ('room_des', models.TextField(blank=True)),
                ('price', models.IntegerField()),
                ('image1', models.ImageField(blank=True, upload_to='rooms')),
                ('image2', models.ImageField(blank=True, upload_to='rooms')),
                ('image3', models.ImageField(blank=True, upload_to='rooms')),
                ('image4', models.ImageField(blank=True, upload_to='rooms')),
            ],
        ),
    ]
