# Generated by Django 3.2.2 on 2021-05-09 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival_date', models.DateField(auto_now=True, null=True)),
                ('departure_date', models.DateField(auto_now=True, null=True)),
                ('room_select', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='0', max_length=255, null=True)),
                ('num_rooms', models.IntegerField(null=True)),
                ('num_person', models.IntegerField(null=True)),
                ('num_children', models.IntegerField(null=True)),
                ('phone_num', models.IntegerField(null=True)),
                ('des', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
