# Generated by Django 3.2.2 on 2021-05-09 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_mybooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='mybooking',
            name='num_nights',
            field=models.IntegerField(null=True),
        ),
    ]
