# Generated by Django 3.2.2 on 2021-05-09 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_mybooking_num_nights'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mybooking',
            name='num_rooms',
        ),
    ]
