# Generated by Django 3.2.2 on 2021-05-09 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_mybooking_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mybooking',
            name='num_children',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
