# Generated by Django 3.2.2 on 2021-05-09 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_alter_mybooking_num_children'),
    ]

    operations = [
        migrations.AddField(
            model_name='mybooking',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.roomdetails'),
        ),
    ]
