# Generated by Django 3.2.2 on 2021-05-09 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_auto_20210509_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='heading',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
