# Generated by Django 3.2.2 on 2021-05-10 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_gallery_heading'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='heading',
        ),
    ]
