# Generated by Django 3.2.2 on 2021-05-18 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0018_auto_20210518_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='mybooking',
            name='arrival_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='mybooking',
            name='departure_date',
            field=models.DateField(null=True),
        ),
    ]
