# Generated by Django 3.2.2 on 2022-04-16 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0022_auto_20220416_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(blank=True, choices=[('men', 'men'), ('women', 'women'), ('children', 'children')], max_length=50, null=True),
        ),
    ]
