# Generated by Django 3.2.2 on 2022-04-16 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0023_product_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='photo',
            new_name='product',
        ),
    ]
