# Generated by Django 3.2.2 on 2022-04-23 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0026_auto_20220423_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='status',
            field=models.CharField(choices=[(0, 'shopping'), (1, 'complete')], default=0, max_length=100),
        ),
    ]
