# Generated by Django 3.2.2 on 2022-05-07 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0030_billingdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingdetails',
            name='cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.cart'),
        ),
        migrations.AlterField(
            model_name='billingdetails',
            name='phone',
            field=models.IntegerField(blank=True, max_length=100, null=True),
        ),
    ]
