# Generated by Django 3.2.2 on 2023-01-06 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0034_blogpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=50, null=True)),
                ('Email', models.EmailField(blank=True, max_length=254, null=True)),
                ('Phone', models.IntegerField(blank=True, null=True)),
                ('Message', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProjectDuration', models.CharField(blank=True, max_length=500, null=True)),
                ('ProjectTitle', models.CharField(blank=True, max_length=500, null=True)),
                ('ProjectDescription', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='intro',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.CreateModel(
            name='BlogImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('Image', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='pages.blogpost')),
            ],
        ),
    ]
