# Generated by Django 3.2.2 on 2023-01-21 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0035_auto_20230106_1440'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogimage',
            name='Image',
        ),
        migrations.AddField(
            model_name='blogimage',
            name='post',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='blog_images', to='pages.blogpost'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
