# Generated by Django 3.2.2 on 2023-01-21 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0036_auto_20230121_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='photos/projects/%Y/%m/%d/'),
        ),
    ]
