# Generated by Django 3.2.2 on 2023-01-24 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0039_funding'),
    ]

    operations = [
        migrations.AddField(
            model_name='funding',
            name='Date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
