# Generated by Django 3.2.2 on 2023-02-02 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0040_funding_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Funding',
        ),
    ]
